// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"moonChat/feed/internal/biz"
	"moonChat/feed/internal/conf"
	"moonChat/feed/internal/data"
	"moonChat/feed/internal/mq"
	"moonChat/feed/internal/server"
	"moonChat/feed/internal/service"
	"moonChat/mqInterface/api/msgQueue/v1"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	greeterRepo := data.NewGreeterRepo(dataData, logger)
	mqAdm := v1.NewMqAdm()
	mqMQ := mq.NewMQ(mqAdm)
	greeterMQ := mq.NewGreeterMQ(mqMQ, logger)
	greeterUsecase := biz.NewGreeterUsecase(greeterRepo, greeterMQ, logger)
	greeterService := service.NewGreeterService(greeterUsecase)
	grpcServer := server.NewGRPCServer(confServer, greeterService, logger)
	httpServer := server.NewHTTPServer(confServer, greeterService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
